// GRAPHICS.H

#define PIOVER180	0.017453292519943295769236907684886

SDL_Surface *screen;
SDL_Surface *prueba;



/*


int eDIV_XPUT(FUNCTION_PARAMS);
int eDIV_MAP_PUT(FUNCTION_PARAMS);

int eDIV_SETPOS(FUNCTION_PARAMS);
int eDIV_fade(FUNCTION_PARAMS);
int eDIV_LOAD_MAP(FUNCTION_PARAMS);
int eDIV_SET_MODE(FUNCTION_PARAMS);
int eDIV_LOAD_FPG(FUNCTION_PARAMS);
int eDIV_UNLOAD_FPG(FUNCTION_PARAMS);
int eDIV_UNLOAD_MAP(FUNCTION_PARAMS);
*/
int eDIV_LOAD_BMP(FUNCTION_PARAMS);
int eDIV_COLLISION(FUNCTION_PARAMS);
int eDIV_SET_TRASPARENT_COLOR(FUNCTION_PARAMS);
int eDIV_GET_TRASPARENT_COLOR(FUNCTION_PARAMS);
int eDIV_RGB(FUNCTION_PARAMS);
int eDIV_ADVANCE(FUNCTION_PARAMS);
int eDIV_XADVANCE(FUNCTION_PARAMS) ;
int eDIV_MAP_BLOCK_COPY(FUNCION_PARMAS) ;
int eDIV_MAP_GET_PIXEL(FUNCION_PARMAS) ;
int eDIV_MAP_PUT(FUNCION_PARMAS) ;
int eDIV_MAP_PUT_PIXEL(FUNCTION_PARAMS);
int eDIV_PUT(FUNCTION_PARAMS);
int eDIV_PUT_PIXEL(FUNCTION_PARAMS);
int eDIV_PUT_SCREEN(FUNCION_PARAMS);
int eDIV_CLEAR_SCREEN(FUNCTION_PARAMS);
int eDIV_GET_PIXEL(FUNCTION_PARAMS);
int eDIV_NEW_MAP(FUNCTION_PARAMS) ;
int eDIV_SCREEN_COPY(FUNCTION_PARAMS) ;
int eDIV_OUT_REGION(FUNCTION_PARAMS) ;
int eDIV_DRAW(FUNCTION_PARAMS) ;
int eDIV_MOVE_DRAW(FUNCTION_PARAMS) ;
int eDIV_DELETE_DRAW(FUNCTION_PARAMS) ;
int eDIV_LOAD_FPG(FUNCTION_PARAMS) ;
int eDIV_GET_POINT(FUNCTION_PARAMS) ;
int eDIV_GET_REAL_POINT(FUNCTION_PARAMS) ;
int eDIV_GRAPHIC_INFO(FUNCTION_PARAMS) ;
int eDIV_FADE(FUNCTION_PARAMS) ;

int Dibuja(SDL_Surface *src , SDL_Rect srcrect , SDL_Rect dstrect , int z , int trans );
